print('-'*80, end='\n\n')
print("Числа:", end='\n\n')
print("int('3'):", int('3'))
print("int(3.1415):", int(3.1415))
print("float(3):", float(3))
print("float(3.4):", float(3.4))
print("float('3.4'):", float('3.4'))
print("float(3E4):", float('3E4'), end='\n\n')
print('-'*80, end='\n\n')
a = [1, 2]
print("Строки:", end='\n\n')
print("a = [1, 2], str(a), type(str(a)):", str(a), type(str(a)))
print("str(255):", str(a))
print("str(25.5):", str(a))
print("str(True), type(str(True)):", str(True), type(str(True)), end='\n\n')
print('-'*80, end='\n\n')
print("Логические значения:", end='\n\n')
print("bool(''):", bool(''))
print("bool('1'):", bool('1'))
print("bool('0'):", bool('0'))
print("bool('True'), type(bool('True')):", bool('True'), type(bool('True')))
print("bool('False'), type(bool('False')):", bool('False'), type(bool('False')))
print("bool(1):", bool(1))
print("bool(0):", bool(0))
print("bool(['a']):", bool(['a']))
print("bool([]):", bool([]), end='\n\n')
print('-'*80, end='\n\n')
print("Словари:", end='\n\n')
init_list = [['key_1', 1], ['key_2', 2], ['key_3', 3]]
print("init_list = [['key_1', 1], ['key_2', 2], ['key_3', 3]], dict(init_list):", dict(init_list))
init_str = "{ 'key_1': 1, 'key_2': 2, 'key_3': 3 }"
print("init_str = \"{ 'key_1': 1, 'key_2': 2, 'key_3': 3 }\", eval(init_str):", eval(init_str)) # ! НЕбезопасная функция !
import ast
print("ast.literal_eval(init_str):", ast.literal_eval(init_str))
